# This workflow builds the project with Gradle, generates coverage reports,
# and pushes the reports to Codecov
name: build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run checks and tests
        run: ./gradlew check
      - name: Upload analysis to GitHub
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: check-results
          path: build/reports
          if-no-files-found: error

